version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Python environment
python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

